# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift-testing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Cartography'

  target 'swift-testing Tests' do
    pod 'Nimble'
    pod 'Quick'
    pod 'Nimble-Snapshots'
    
    pod 'KIF'
    pod 'KIF-Quick'
  end

end
